spring.jpa.show-sql: true
server.port: 8890

#security:
#  oauth2:
#    client:
#      clientId: ${clientId}
#      clientSecret: ${clientSecret}
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
